FROM golang:1.12-alpine3.9 as builder

RUN apk update && apk add --no-cache git

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /app/api-gateway
RUN chmod +x /app/api-gateway

FROM scratch

COPY --from=builder /app/api-gateway /app/api-gateway

ENTRYPOINT ["/app/api-gateway"]
