version: '3.7'

services:
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx/.
        ports:
            - '8000:433'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/etc/nginx/conf.d
        links:
            - chat-server

    chat-server:
        container_name: chat-server
        build: 
            dockerfile: Dockerfile
            context: chat-server/
        volumes:
            - .:/app
        expose:
            - '433'
        depends_on:
            - mariadb
            - redis
        restart: on-failure
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_NAME=chat_server
            - DB_USER=root
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DEPLOYMENT_TYPE=local

    redis:
        container_name: redis
        restart: always
        image: redis:alpine
        expose:
            - '6379'
    
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        expose:
            - '3306'
        volumes:
            - ./testing/:/docker-entrypoint-initdb.d/

    start_dependencies:
        image: jwilder/dockerize
        depends_on:
            - mariadb
            - redis
        command: dockerize -wait tcp://mariadb:3306 -wait tcp://redis:6379 -timeout 5m

