version: '3.7'

services:
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx/.
        ports:
            - '8000:433'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/etc/nginx/conf.d
        links:
            - api-gateway

    api-gateway:
        container_name: api-gateway
        build: 
            dockerfile: Dockerfile
            context: api-gateway/
        volumes:
            - .:/app
        expose:
            - '433'
        depends_on:
            - mariadb
            - redis
        restart: on-failure
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_NAME=api_gateway
            - DB_USER=root
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DEPLOYMENT_TYPE=local

    redis:
        container_name: redis
        restart: always
        image: redis:alpine
        expose:
            - '6379'
    
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        expose:
            - '3306'
        volumes:
            - ./testing/:/docker-entrypoint-initdb.d/

    start_dependencies:
        image: jwilder/dockerize
        depends_on:
            - mariadb
            - redis
        command: dockerize -wait tcp://mariadb:3306 -wait tcp://redis:6379 -timeout 5m

    start_api-gateway:
        image: jwilder/dockerize
        depends_on:
            - nginx
            - api-gateway
        command: dockerize -wait tcp://api-gateway:433 -timeout 10s

