version: '3.7'

services:
    nginx:
        restart: always
        build: ./nginx/.
        ports:
            - '8000:433'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/etc/nginx/conf.d

    api-gateway:
        build: 
            dockerfile: Dockerfile
            context: api-gateway/
        volumes:
            - .:/app
        expose:
            - '433'

    chat-server:
        build:
            dockerfile: Dockerfile
            context: chat-server/
        expose:
            - '3000'

    redis-session:
        image: redis
        expose:
            - '6379'
    redis-chat:
        image: redis
        expose:
            - '7379'
